CXXFLAGS = -Wall -I/home/luqui/devel/soylent/open/soylib/include -O2 -g `sdl-config --cflags`
LDLIBS = `sdl-config --libs` -lGL -lGLU -lfftw3 /home/luqui/devel/soylent/open/soylib/src/libsoy.so.1 -lSDL_mixer

all: main
